
local PLUGIN = PLUGIN
local cpoutfit = cpoutfit

function PLUGIN:InitializedPlugins()
    cpoutfit.AddModel("models/metropolice/c08.mdl")
    cpoutfit.AddModel("models/metropolice/c08_female.mdl")
    cpoutfit.AddModel("models/metropolice/c08_female_2.mdl")
    cpoutfit.AddModel("models/metropolice/c08_female_3.mdl")

    cpoutfit.AddMaterialPart("uniform", nil, nil, "Uniform")
    cpoutfit.AddMaterialID("uniform", "models/metropolice/c08.mdl", 0)
    cpoutfit.AddMaterialID("uniform", "models/metropolice/c08_female.mdl", 0)
    cpoutfit.AddMaterialID("uniform", "models/metropolice/c08_female_2.mdl", 0)
    cpoutfit.AddMaterialID("uniform", "models/metropolice/c08_female_3.mdl", 0)
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_default", 0, "Default")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_medic", nil, "Medic")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_vice", nil, "PHANTOM")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_elite", nil, "Elite #1")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_resistance", nil, "Rebel")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_digital", nil, "Digital Camo")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_cmd", nil, "'CmD'")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_ghost", nil, "'GHOST'")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_shock", nil, "'SHOCK'")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_elite2", nil, "Elite #2")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_sec", nil, "'SeC'")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_concept", nil, "Concept")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_arctic", nil, "Arctic")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_cmr", nil, "CmR")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_disbat", nil, "Disbat")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_elite3", nil, "Elite #3")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_elite4", nil, "Elite #4")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_grid", nil, "GRID")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_other", nil, "Other")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_sec2", nil, "SeC Demension")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_union", nil, "UNION")
    cpoutfit.AddMaterialOverride("uniform", "models/metropolice/uniform_white_elite", nil, "White Elite")

    cpoutfit.AddMaterialPart("gasmask_style", nil, nil, "Gasmask texture")
    cpoutfit.AddMaterialID("gasmask_style", "models/metropolice/c08.mdl", 4)
    cpoutfit.AddMaterialID("gasmask_style", "models/metropolice/c08_female.mdl", 4)
    cpoutfit.AddMaterialID("gasmask_style", "models/metropolice/c08_female_2.mdl", 4)
    cpoutfit.AddMaterialID("gasmask_style", "models/metropolice/c08_female_3.mdl", 4)
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_light_3", 0, "Default (Rear Side lights)" )
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_white_3", nil, "Light Green (Rear Side lights)")
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_black_3", nil, "Black (Rear Side lights)")
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_light_2", nil, "Default (Rear Side-Top lights)")
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_white_2", nil, "Light Green (Rear Side-Top lights)")
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_black_2", nil, "Black (Rear Side-Top lights)")
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_light", nil, "Default (Rear Side-Top-Front lights)")
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_white", nil, "Light Green (Rear Side-Top-Front lights)")
    cpoutfit.AddMaterialOverride("gasmask_style", "models/metropolice/gasmask_black", nil, "Black (Rear Side-Top-Front lights)")

    cpoutfit.AddMaterialPart("gasmaskshock_style", nil, nil, "Gasmask_shock texture")
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/metropolice/c08.mdl", 23)
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/metropolice/c08_female.mdl", 21)
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/metropolice/c08_female_2.mdl", 21)
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/metropolice/c08_female_3.mdl", 21)
    cpoutfit.AddMaterialOverride("gasmaskshock_style", "models/metropolice/gasmask_shock_white", 0, "Default")
    cpoutfit.AddMaterialOverride("gasmaskshock_style", "models/metropolice/gasmask_shock_black", nil, "Black")
    cpoutfit.AddMaterialOverride("gasmaskshock_style", "models/metropolice/gasmask_shock_white_2", nil, "Light")

    cpoutfit.AddMaterialPart("visor_style", nil, nil, "Lenses (for mask_0,1,2,6 mdls)")
    cpoutfit.AddMaterialID("visor_style", "models/metropolice/c08.mdl", 18)
    cpoutfit.AddMaterialID("visor_style", "models/metropolice/c08_female.mdl", 18)
    cpoutfit.AddMaterialID("visor_style", "models/metropolice/c08_female_2.mdl", 18)
    cpoutfit.AddMaterialID("visor_style", "models/metropolice/c08_female_3.mdl", 18)
    cpoutfit.AddMaterialOverride("visor_style", "models/metropolice/standard_lens_noglow", 0, "Default")
    cpoutfit.AddMaterialOverride("visor_style", "models/metropolice/standard_lens_glow", nil, "Glow-compatible texture")

    cpoutfit.AddMaterialPart("armband", nil, nil)
    cpoutfit.AddMaterialID("armband", "models/metropolice/c08.mdl", 1)
    cpoutfit.AddMaterialID("armband", "models/metropolice/c08_female.mdl", 3)
    cpoutfit.AddMaterialID("armband", "models/metropolice/c08_female_2.mdl", 3)
    cpoutfit.AddMaterialID("armband", "models/metropolice/c08_female_3.mdl", 3)

    cpoutfit.AddModel("models/player/metropolice/c08.mdl")
    cpoutfit.AddModel("models/player/metropolice/c08_female.mdl")
    cpoutfit.AddModel("models/player/metropolice/c08_female_2.mdl")
    cpoutfit.AddModel("models/player/metropolice/c08_female_3.mdl")
    cpoutfit.AddMaterialID("uniform", "models/player/metropolice/c08.mdl", 0)
    cpoutfit.AddMaterialID("uniform", "models/player/metropolice/c08_female.mdl", 0)
    cpoutfit.AddMaterialID("uniform", "models/player/metropolice/c08_female_2.mdl", 0)
    cpoutfit.AddMaterialID("uniform", "models/player/metropolice/c08_female_3.mdl", 0)
    cpoutfit.AddMaterialID("gasmask_style", "models/player/metropolice/c08.mdl", 4)
    cpoutfit.AddMaterialID("gasmask_style", "models/player/metropolice/c08_female.mdl", 4)
    cpoutfit.AddMaterialID("gasmask_style", "models/player/metropolice/c08_female_2.mdl", 4)
    cpoutfit.AddMaterialID("gasmask_style", "models/player/metropolice/c08_female_3.mdl", 4)
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/player/metropolice/c08.mdl", 23)
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/player/metropolice/c08_female.mdl", 21)
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/player/metropolice/c08_female_2.mdl", 21)
    cpoutfit.AddMaterialID("gasmaskshock_style", "models/player/metropolice/c08_female_3.mdl", 21)
    cpoutfit.AddMaterialID("visor_style", "models/player/metropolice/c08.mdl", 18)
    cpoutfit.AddMaterialID("visor_style", "models/player/metropolice/c08_female.mdl", 18)
    cpoutfit.AddMaterialID("visor_style", "models/player/metropolice/c08_female_2.mdl", 18)
    cpoutfit.AddMaterialID("visor_style", "models/player/metropolice/c08_female_3.mdl", 18)
    cpoutfit.AddMaterialID("armband", "models/player/metropolice/c08.mdl", 1)
    cpoutfit.AddMaterialID("armband", "models/player/metropolice/c08_female.mdl", 3)
    cpoutfit.AddMaterialID("armband", "models/player/metropolice/c08_female_2.mdl", 3)
    cpoutfit.AddMaterialID("armband", "models/player/metropolice/c08_female_3.mdl", 3)

    hook.Run("CPOutfit.LoadParameters")
end